# Generated by Django 5.2.5 on 2025-09-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='tag',
        ),
    ]
