# Generated by Django 5.2.5 on 2025-09-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_alter_article_id_arttagrelation_delete_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_main',
        ),
        migrations.AddField(
            model_name='arttagrelation',
            name='is_main',
            field=models.BooleanField(null=True),
        ),
    ]
