# Generated by Django 5.2.5 on 2025-09-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_tag_is_main_arttagrelation_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttagrelation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
