# Generated by Django 5.2.5 on 2025-09-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_rename_tags_article_scopes_alter_scope_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='topic',
        ),
    ]
