# Generated by Django 5.2.5 on 2025-09-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_rename_tag_scope_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='topic',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='topic',
        ),
    ]
