# Generated by Django 5.2.5 on 2025-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_rename_topic_scope_tag_rename_name_tag_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.article'),
        ),
    ]
