# Generated by Django 5.2.5 on 2025-09-02 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_alter_scope_tag_alter_tag_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scopes',
            field=models.ManyToManyField(through='articles.Scope', to='articles.article'),
        ),
    ]
