# Generated by Django 5.2.5 on 2025-09-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_scope_article_alter_tag_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='scopes',
        ),
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
    ]
