# Generated by Django 5.2.5 on 2025-09-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_rename_tag_scope_topic_remove_tag_scopes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
