
http://127.0.0.1:8000/sensor/8/

###

POST http://127.0.0.1:8000/

###

POST http://127.0.0.1:8000/sensors/
Content-Type: application/json

{
  "name": "4444",
  "description": "Датчик на "
}

###

UPDATE

###




###




###




###
